# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7593f184bac098cf76796b9026f062f4b7b567946e00b2402224a75f447f362efc9affdabb32c6809f416bd29b3bea5369b50104b27065a3b1eedb20e5fe50

test:
  secret_key_base: ce7db05a667209c795b916ca9d57ff7e2cb55f8f9c6a637110a607994b901810e50885b78a36c338852107e1d88b742bdf6f437a52a2b04bec938760ae4c6b7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
